name : BackEnd CD Workflow

on:
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - main
    paths:
      - "starter/backend/**"

env:
  PYTHON_VERSION: 3.12
  EKS_CLUSTER_NAME: cluster

jobs:
  lint:
    name: run lint BackEnd
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: starter/backend/
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: cache pipenv environment
        uses: actions/cache@v2
        with:
          path: |
            ~/.local/share/virtualenvs
            .venv
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: setup python environment
        uses: actions/setup-python@v4
        with: 
          python-version: ${{env.PYTHON_VERSION}}

      - name : install dependencies
        run: |
          pip install pipenv
          pipenv install
          pip install flake8

      - name: run lint
        run: pipenv run lint

  test:
    name: run test BE
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend/
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: cache pipenv environment
        uses: actions/cache@v2
        with:
          path: |
            ~/.local/share/virtualenvs
            .venv
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: setup python environment
        uses: actions/setup-python@v4
        with: 
          python-version: ${{env.PYTHON_VERSION}}
      
      - name : install dependencies
        run: |
          pip install pipenv
          pipenv install
          pip install flake8

      - name: run tests
        run: pipenv run test

  build:
    name: build and run BackEnd
    needs: [lint, test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend/
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: cache pipenv environment
        uses: actions/cache@v2
        with:
          path: |
            ~/.local/share/virtualenvs
            .venv
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: setup python environment
        uses: actions/setup-python@v4
        with: 
          python-version: ${{env.PYTHON_VERSION}}

      - name : install dependencies
        run: |
          pip install pipenv
          pipenv install
          pip install flake8

      - name: setup aws
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: backend
        run: |
          git_sha=$(git rev-parse --short HEAD)
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$git_sha .
          docker images
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$git_sha
        
  deploy:
    name: deploy to EKS
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: starter/backend/
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: get cluster certificate
        run: |
          aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }}
        
      - name: add github action user to kubernetes
        working-directory: setup
        run: |
          ./init.sh || true

      - name: set docker image for kustomize
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: backend
        working-directory: starter/backend/k8s
        run: |
          git_sha=$(git rev-parse --short HEAD)
          kustomize edit set image backend=$REGISTRY/$REPOSITORY:$git_sha
      
      - name: apply the manifests to the cluster
        working-directory: starter/backend/k8s
        run: kustomize build | kubectl apply --validate=false -f -
